version: "3.3"

services:
  mystash:
    image: mystash
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - API_PORT=3000
      - DB_URI=mongodb://mongo/mystash
      - TEST_DB_URI=mongodb://mongo/mystash-test
      - JWT_SECRET= GENERATE WITH node -e "console.log(require('crypto').randomBytes(256).toString('base64'));"
      - NODE_ENV=production
    depends_on:
      - mongo
    
  mongo:
    image: mongo:latest
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config: